name: Feature request
description: Suggest an idea
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: What would you like to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
